export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVE_FOR_LATER = "SAVE_FOR_LATER";
export const REMOVE_FROM_LATER = "REMOVE_FROM_LATER";
export const SUBTRACT_ITEM_FROM_CART = "SUBTRACT_ITEM_FROM_CART";